site_name: CLR MD
docs_dir: Documentation
pages:
- Introduction: index.md
- Tutorial:
  - Getting Started: GettingStarted.md
  - ClrRuntime: ClrRuntime.md
  - Walking the Heap: WalkingTheHeap.md
  - Types and Fields: TypesAndFields.md
  - Machine Code: MachineCode.md
- FAQ: FAQ.md
